### PR TITLE
Diagram of high-level relationships between WoT documents

### PR DESCRIPTION
**Pull request by k-toumura**
I've drawn a diagram to make it easier to understand the WoT documents at a glance.
It is not necessary to incorporate it into the charter document, but I think it will be useful to organize the relationships between the documents for future detailed discussions.

By separating documents that take a prescriptive approach from those that take a descriptive approach, I believe it will be easier to understand what each document should specify.

Note: The diagram is edited using [diagrams.net](https://www.diagrams.net/)(draw.io).  Please edit the `specs.drawio` file when editing. Due to [limitations](https://www.diagrams.net/doc/faq/svg-export-text-problems), the SVG file will not be displayed properly in other programs such as Inkscape.

### CODE REVIEW

**Comment by egekorkan** [comment]
@k-toumura thank you for this, I think that it is pretty good and I do not see any major problems. One thing regarding discovery is that it can be added on top of a brownfield system to manage the TDs that are generated later on. So it is not strictly for greenfield systems. Since you say "mainly", I think that it is fine to merge this diagram as is.

**Comment by mlagally** [comment]
@k-toumura 
Many thanks for this diagram, which could be included into a future version of the architecture specification.
Adding colours to the diagram would be useful.

**Comment by mlagally** [comment]
Updated with colours, a bit of reformatting

specs drawio drawio txt drawio

**Comment by egekorkan** [comment]
I prefer the first one without bold titles

**Comment by k-toumura** [comment]
Thank you, @egekorkan and @mlagally .
I updated the diagram based on @mlagally 's comment.

BTW, when exporting SVG with draw.io, it would be better to embed fonts so that the layout will not be corrupted.
image

**Review by mmccool — APPROVED** [review]
OK with this diagram.  Discovery itself is a prescriptive spec, but yes, it's not only for greenfield devices.  But we can refine later.  It would be good to embed fonts as Ege suggests.  For the record though I dislike having diagrams that are not editable as normal SVG.

**Comment by sebastiankb** [comment]
I like this overview. Lets discuss this in tomorrows planning session.

**Comment by sebastiankb** [comment]
from today's planning session: decided to merge

**Pull request merged**
