### PR TITLE
Move IG mention to collaboration section

### LINKED ISSUE #65: Move IG Relationship from Mission Statement to Collaboration
Coming from the charter call on 27.02.2023

In the charter, we should make clear what kind of collaboration we have with other groups, including WoT IG. Below are the texts in question:

- This Working Group Charter covers those aspects that the [Web of Things Interest Group](http://www.w3.org/groups/ig/wot) [(charter here)](https://www.w3.org/2021/12/wot-ig-2021.html) believes are mature enough to progress to W3C Recommendations.
- As a continuation of the work in [the previous charter](https://www.w3.org/2022/07/wot-wg-2022.html), this working group is tasked with the standardization or extension of the building blocks identified by the use cases resulting from the work of [the Web of Things Interest Group](https://www.w3.org/groups/ig/wot) (IG) as being important to advance the Web of Things.

The first PR should move these to the coordination section and then another should provide a diagram that explains the relationships.

### PR DESCRIPTION
**Pull request by egekorkan**
I am doing a very simple move of the text without changing any content so that we avoid a lengthy discussion on this particular point. Later on, I will make another PR to actually change the content and explain what the relationship is. Given that #65 was made during the call on what we seem to agree on, this should be easily mergable.

fixes #65

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-charter-drafts/pull/66.html" title="Last updated on Mar 27, 2023, 11:45 AM UTC (a61f867)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-charter-drafts/66/8dbe03d...a61f867.html" title="Last updated on Mar 27, 2023, 11:45 AM UTC (a61f867)">Diff</a>

### CODE REVIEW

**Comment by mmccool** [comment]
Moved text is a little weird and needs some cleanup but I agree we should move it in one PR, then clean it up in another.  Agree with merging.

**Comment by mmccool** [comment]
Improvements:
- Put WoT groups in a section of their own under collaborations
- Move IG to the top, to emphasize its special status

**Comment by egekorkan** [comment]
@mmccool I have incorporated your first feedback. I am not sure what you exactly mean by the special status of the WoT IG. Any changes to the text of the IG should be done in another PR. Let's not make it more complicated here.

**Review by sebastiankb — APPROVED** [review]

**Comment by mmccool** [comment]
We discussed this in the call on March 27 and agreed on a compromise: remove the mention of the IG from the mission statement (note the text has not been lost, but moved to the collaboration section) but keep the link in the background and motivation section.

**Pull request merged**
