### PR TITLE
Add consumer description topics

### PR DESCRIPTION
**Pull request by egekorkan**
As mentioned by @mlagally , a description of what the Thing should do for a given Consumer is missing. We have discussed this internally a bit and there can be a real use of it. However, I am not sure to if we should commit to a REC deliverable since we lack experience in this direction. We can do more experimentation on this and publish a note that becomes a REC later on.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-charter-drafts/pull/89.html" title="Last updated on Mar 13, 2023, 10:25 AM UTC (6761c54)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-charter-drafts/89/0dae730...6761c54.html" title="Last updated on Mar 13, 2023, 10:25 AM UTC (6761c54)">Diff</a>

### CODE REVIEW

**Comment by mmccool** [comment]
We should in general what to do about things that need more incubation before we commit to them.  Onboarding might also be in this category.  I personally feel that Consumer descriptions are unnecessary if we think about TDs describing the *API contract* between Consumers and Things (despite the name TD).

**Comment by mmccool** [comment]
Just noticed this is going into the Scope.  I strongly disagree with this.   It should be a work item covered in "details" and implied by "other work for new use cases".

**Comment by egekorkan** [comment]
> It should be a work item covered in "details" and implied by "other work for new use cases".

I would be fine with this if that is what most of us agree on

**Comment by mlagally** [comment]
If there's a need for experiments, this should be handled in the IG. If we know what to do and specify this is a WG task.

**Comment by egekorkan** [comment]
> If there's a need for experiments, this should be handled in the IG. If we know what to do and specify this is a WG task.

I just wanted to include it since you saw it as a gap. I agree that we lack experience on this and we did not do much experimentation in the plugfests (IG activity). So if we think that this is an important topic, we should:
- Wait for IG to figure out what is needed and what works, then put it into our 3.0 charter if this is needed.
- Wait for IG to figure out what is needed and what works, publish it as part of our 2.0 charter as a note.

**Comment by mmccool** [comment]
OK, seems we do not have consensus on including this in the charter, so I would like to propose closing without merging.  Please propose another way to address this (e.g. a PR for a work item in details that we can discuss while doing detailed planning).

Proposal: Close without Merging

**Comment by mmccool** [comment]
Will close without merging, but another PR to create a work item against the "detail" document for Consumer descriptions, as an "evaluation".   Note: we will eventually clean up the "details" and related technical issues to the wot repo.

**Pull request closed without merging**
