### PR TITLE
Remove details

### LINKED ISSUE #63: Remove detailed work items from charter
- Delete detailed work items from charter
- Capture consolidation work as appropriate to update "details" document
- Leave link to details document in charter

### PR DESCRIPTION
**Pull request by mmccool**
Resolves #63 
- Move consolidated work items from draft charter to details document
- Keep link to details document in charter, but add paragraph tags
- Run details document through html tidy with following command, which cleans up tags but also pretty-prints so structure is clear.
```bash
tidy --drop-empty-elements no -i -w 120 -m wot-wg-2023-details.html
```
- Remove duplicate work items from consolidated list
- When a new work item has consolidated work items from the old list, use as a "section header" and group consolidated items under it
- If there is a *new* work item in the consolidated list add it to the expanded list (none found)
- Add "other" category so groupings consistent, and reorder
- NEW: added "subject to change" clause to details document reference, more clearly indicating its non-binding status

***
<a href="https://pr-preview.s3.amazonaws.com/mmccool/wot-charter-drafts/pull/64.html" title="Last updated on Feb 24, 2023, 2:26 PM UTC (df27a41)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-charter-drafts/64/1c3ac1c...mmccool:df27a41.html" title="Last updated on Feb 24, 2023, 2:26 PM UTC (df27a41)">Diff</a>

### CODE REVIEW

**Comment by mmccool** [comment]
Ack, due to a mistake with how I did the APA removal that was included in this PR.  Will revert.  Sigh...

**Comment by benfrancis** [comment]
@mmccool This PR moves all of the detailed work items to a separate details document, and consolidates them with other text which had previously been summarised in the charter. Is the contents of the linked details document part of the charter as a fixed set of work items? Does the group need to reach a consensus on all of that additional content before the charter can be published, or is it just a starting point for planning?

It would be quicker to get consensus on a high level summary than the more detailed text in the details document, but the proposed summary has far less detail than the last charter. If the work items in the details document are not completely fixed in the charter then perhaps an addition of a simple "which is subject to change" on the note about the details document would clarify? I have some potentially tricky unresolved issues with the detailed work items (e.g. #14 and #57) in the consolidated details.html which need not apply to a high level summary.

Please also see my [minor review feedback](https://github.com/w3c/wot-charter-drafts/pull/52#pullrequestreview-1307454693) on the summary which was not addressed before merging.

**Comment by mmccool** [comment]
> It would be quicker to get consensus on a high level summary than the more detailed text in the details document, but the proposed summary has far less detail than the last charter. If the work items in the details document are not completely fixed in the charter then perhaps an addition of a simple "which is subject to change" on the note about the details document would clarify? I have some potentially tricky unresolved issues with the detailed text (e.g. #14 and #57) in the consolidated details.html which need not apply to a high level summary.

That was my intention: to keep the details for planning (which we definitely need to do, and once we have a plan, we need to follow it...) and let reviewers look at them if they want, but to focus on improving the high-level summary until we have consensus.  However, adding the phrase "subject to change" to the link to the details would make their status clear, so let me do that...

**Comment by mmccool** [comment]
Also, I've kept the details document as HTML so if for some reason we want to move them back into the charter we can still do that.  But it would be best to have all the details in one place rather than trying to sync redundant copies.

**Pull request merged**
