### PR TITLE
Add Architecture as an informative deliverable

### PR DESCRIPTION
**Pull request by egekorkan**
As alternative of #82

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/wot-charter-drafts/pull/85.html" title="Last updated on Mar 8, 2023, 4:35 PM UTC (f673408)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/wot-charter-drafts/85/0dae730...f673408.html" title="Last updated on Mar 8, 2023, 4:35 PM UTC (f673408)">Diff</a>

### CODE REVIEW

**Comment by mlagally** [comment]
This proposal by itself is just moving the contribution from #82 without describing what should happen to the normative parts.
To be acceptable, the PR should propose what should happen with the normative parts of the architecture specification.

**Review by mlagally — CHANGES_REQUESTED** [review]
This PR is not sufficient, since it does not resolve open questions from the discussion in #82.
Let's continue the discussion in #82.

**Comment by egekorkan** [comment]
> To be acceptable, the PR should propose what should happen with the normative parts of the architecture specification.

This is too soon to say that. The group should simply decide what the goal of the architecture specification really is. Also, nobody is implementing so many of the normative parts of the arch 1.1 and they were not tested at all in 1.0 so there is no risk (or very little) of breaking implementations. Plus, even if some of those assertions become informative text, they would not break interoperability since they are about a specific implementation behavior.

**Comment by mmccool** [comment]
Decided to go with the alternative, PR #82.

**Pull request closed without merging**
